<a href="https://colab.research.google.com/github/creamburger/TensorStudy/blob/main/2%EA%B0%95_%EB%B3%80%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
my_variable = tf.Variable(tf.ones([1, 2, 3]))

In [ ]:
my_variable

<tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
with tf.device("/device:GPU:1"):
  my_variable = tf.ones([10, 10])


In [ ]:
my_variable

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
v = tf.Variable(0.0)
w = v + 1

In [ ]:
w

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [ ]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>

In [ ]:
v.assign_add(1.0)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=1.0>

In [ ]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [ ]:
v.read_value()

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [ ]:
class MyModuleOne(tf.Module):
  def __init__(self):
    self.v0 = tf.Variable(1.0)
    self.vs = [tf.Variable(x) for x in range(10)]

class MyOtherModule(tf.Module):
  def __init__(self):
    self.m = MyModuleOne()
    self.v = tf.Variable(10.0)

In [ ]:
m = MyOtherModule()

In [ ]:
len(m.trainable_variables)

12